<a href="https://colab.research.google.com/github/james-lucius/QURECA_ADEQUATE/blob/main/M2_1_5_1_Probablistic_Operators_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://gitlab.com/qworld/qeducation/educational-materials/adequate-qbook1/raw/main/qworld/images/adq_1.png" align="left" width=450></a>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\stateplus}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\stateminus}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\I}{ \mymatrix{rr}{1 & 0 \\ 0 & 1}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $
$ \newcommand{\pstate}[1]{ \lceil \mspace{-1mu} #1 \mspace{-1.5mu} \rfloor } $
$ \newcommand{\greenbit}[1] {\mathbf{{\color{green}#1}}} $
$ \newcommand{\bluebit}[1] {\mathbf{{\color{blue}#1}}} $
$ \newcommand{\redbit}[1] {\mathbf{{\color{red}#1}}} $
$ \newcommand{\brownbit}[1] {\mathbf{{\color{brown}#1}}} $
$ \newcommand{\blackbit}[1] {\mathbf{{\color{black}#1}}} $

_prepared by Abuzer Yakaryilmaz_

<font size="28px" style="font-size:28px;" align="left"><b> <font color="blue"> Exercises for </font>Probabilistic Operators </b></font>

##### <font color="#08b806">Please execute the following cell, it is necessary to distinguish between your local environment and Google Colab's

In [1]:
import IPython

def in_colab():
    try:
        import google.colab
        return True
    except:
        return False

SolutionToTask2 = lambda: IPython.display.display(IPython.display.Javascript('window.open("{url}");'.format(url='https://colab.research.google.com/drive/12MousEBp_2vxS249g6j40Xrju3vdIBbF#scrollTo=d8F2QM47H_tD' if in_colab() else 'Probabilistic_Operators_Exercises_Solutions.ipynb#task2')))
SolutionToTask3 = lambda: IPython.display.display(IPython.display.Javascript('window.open("{url}");'.format(url='https://colab.research.google.com/drive/12MousEBp_2vxS249g6j40Xrju3vdIBbF#scrollTo=sJ0Rx2nKH_tD' if in_colab() else 'Probabilistic_Operators_Exercises_Solutions.ipynb#task3')))
SolutionToTask4 = lambda: IPython.display.display(IPython.display.Javascript('window.open("{url}");'.format(url='https://colab.research.google.com/drive/12MousEBp_2vxS249g6j40Xrju3vdIBbF#scrollTo=XA1SUq_LH_tE' if in_colab() else 'Probabilistic_Operators_Exercises_Solutions.ipynb#task4')))
SolutionToTask5 = lambda: IPython.display.display(IPython.display.Javascript('window.open("{url}");'.format(url='https://colab.research.google.com/drive/12MousEBp_2vxS249g6j40Xrju3vdIBbF#scrollTo=o3Dj7oxLH_tF' if in_colab() else 'Probabilistic_Operators_Exercises_Solutions.ipynb#task5')))

#<h3> Task 2 </h3>

We are given the following probabilistic operator: $ B =  \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $.

What is the transition probability from the second state to the third state?

What is the transition probability from the third state to the first state?

What is the transition probability from the first state to the second state?

To check out our solution, run the next cell:

# Solutions to Task 2
second to third = 0.3
third to first = 0
first to second = 0.2

In [ ]:
SolutionToTask2()  # show solution for task 2

<IPython.core.display.Javascript object>

<h3>Task 3</h3>

Randomly construct a $ (3 \times 3 ) $-dimensional probabilistic operator.

That is, randomly determine the entries of the matrix that represents a probabilistic operator.

In [4]:
#
# your solution is here
#
import numpy as np
from random import randrange
probabilistic_operator = np.random.rand(3, 3)
for i in range(3):
  column_i = probabilistic_operator[:, i]
  column_i /= np.sum(column_i)
  probabilistic_operator[:, i] = column_i

for i in range(3):
  for j in range(3):
    probabilistic_operator[i, j] = probabilistic_operator[i, j].round(2)
for row in probabilistic_operator: print(row)

[0.19 0.28 0.26]
[0.27 0.31 0.35]
[0.53 0.4  0.39]


To check out our solution, run the next cell:

In [ ]:
SolutionToTask3()  # show solution for task 3

<h3> Task 4 </h3>

What is the new probabilistic state if the operator $ B =  \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $ is applied to the state $ \myvector{ 0.1 \\ 0.3 \\ 0.6 } $.

Please find the result by using matrix-vector multiplication.

Please do not use any python library for matrix-vector multiplication.

<i> The new probabilistic state should be $ \myvector{0.22 \\ 0.47 \\ 0.31} $. </i>

In [5]:
# operator B
B = [
    [0.4,0.6,0],
    [0.2,0.1,0.7],
    [0.4,0.3,0.3]
]

# the current state
v = [0.1,0.3,0.6]

#
# your solution is here
#
v_new = []
for i in range(3):
  result = 0
  for j in range(3):
    result += B[i][j] * v[j]
  v_new.append(result)

print(v_new)

[0.22, 0.47, 0.31]


To check out our solution, run the next cell:

In [ ]:
SolutionToTask4()  # show solution for task 4

<h3> Task 5 </h3>

Write a function named <i>linear_evolve</i> that takes a probabilistic operator and a probabilistic state, and then returns the new probabilistic state.

Please do not use any python library for matrix-vector multiplication.

Your function should work for any dimension.

Save your function so that you can use it later.
<br>
<div style="background-color:#f8f8f8;">
<b><u>Write the content of a code cell</u></b> into an external file:
    
    %%writefile linear_evolve.py
This command should be placed in the first line of cell, and then the cell should be executed.
</div>

Test your function on $ B = \mymatrix{ccc}{ 0.4 & 0.6 & 0 \\ 0.2 & 0.1 & 0.7 \\ 0.4 & 0.3 & 0.3 } $ and $ \myvector{0.1 \\ 0.3 \\ 0.6} $.

The new probabilistic state should be $ \myvector{0.22 \\ 0.47 \\ 0.31} $.

Then, evolve your system for 5, 10, 20, and 40 steps.

This system should evolve to a fixed probabilistic state.

Change your initial state to  $ \myvector{1 \\ 0 \\ 0} $, and see whether the converged state is the same or not.

In [6]:
%%writefile linear_evolve.py
# define function
def linear_evolve(operator, state):
  new_state = []
  for i in range(len(operator)):
    result = 0
    for j in range(len(state)):
      result += operator[i][j] * state[j]
    new_state.append(result)
  return new_state

Writing linear_evolve.py


In [7]:
# run your script
%run linear_evolve.py

# operator for the test
B = [
    [0.4,0.6,0],
    [0.2,0.1,0.7],
    [0.4,0.3,0.3]
]

# state for test
v = [0.1,0.3,0.6]

#
# your solution is here
#
print(linear_evolve(B, v))

[0.22, 0.47, 0.31]


To check out our solution, run the next cell:

In [ ]:
SolutionToTask5()  # show solution for task 5

---

<h3> Extra: Task 6 </h3>

The operator $ \widetilde{I} = \mymatrix{cc}{0.999 & 0.001\\ 0.001 & 0.999 } $ is very similar to Identity operator. However, it converges to a certain matrix.

Find $  \underbrace{\widetilde{I} \cdot \widetilde{I} \cdots \widetilde{I}}_{k\mbox{ times}} $ for $ k = 10, 100, 1000, 10000, 100000 $ and then guess the converging matrix.

<h3> Extra: Task 7 </h3>

Repeat Task 6 for the operator $ \widetilde{NOT} = \mymatrix{cc}{0.001 & 0.999\\ 0.999 & 0.001 } $.